### ISSUE TITLE
Filtering based on a column with text entries

### ISSUE THREAD

**Issue by emmats** [uwescience/sqlshare#12]
I'm trying to remove data from a dataset based on words in a column, which seems to be more difficult than when it is based on numerical values.  I have a column with the following values: precursor, precursor [M+1], precursor [M+2].  I only want to keep rows that correspond to "precursor".  I have used the following code (Fragmention is the column name):
SELECT \* FROM [emmats@washington.edu].[Skyline Data precursor 2]
  WHERE Fragmention LIKE precursor

And I get this error: Problem running query: Invalid column name 'precursor'.

Thanks!

**Comment by dhalperi** [comment]
Hi!

So, in the code you wrote, SQLShare thinks that `precursor` is a column name. If you want it to try it as a text string, you need to put it in single quotes:

``` sql
SELECT * FROM [emmats@washington.edu].[Skyline Data precursor 2]
WHERE [FragmentIon] like 'precursor'
```

**Comment by dhalperi** [comment]
Also, it will be faster if you write the query like this:

``` sql
SELECT * FROM [emmats@washington.edu].[Skyline Data precursor 2]
WHERE [FragmentIon] = 'precursor'
```

**Comment by dhalperi** [comment]
(The reason the latter is better is that `LIKE` is for pattern matching, whereas `=` requires an exact match. The code that checks pattern matching is slow...)
