### ISSUE TITLE
arithmetic in SQL

### ISSUE THREAD

**Issue by emmats** [uwescience/sqlshare#13]
Thanks for the help yesterday, Dan!  Here's my question of the day...
In my file All proteins with length (https://sqlshare.escience.washington.edu/sqlshare#s=query/emmats%40washington.edu/All%20proteins%20with%20length) I need to perform the following:
1. For each column [CG# total SpC], divide by the column [protein length] and create a new column with these values [SpC/L#](I've been working on this first step with no success, see code below)
2. Get the total sum of each new column [SpC/L#]
3. In a new column [NSAF#] divide every value in the column [SpC/L#] by the sum calculated in step 2

The only other column I need at the end of this is [All Proteins]

Attempted code: SELECT [All Proteins],
  ([CG2 total SpC]/[protein length]) AS [CG2 SpC/L]
  FROM [emmats@washington.edu].[All proteins with length]​

**Comment by dhalperi** [comment]
Great. So your query for (1) looks great, except for one annoying thing: when A and B are both integers, A/B is rounded to the nearest integer. In this case, always 0. To fix this, CAST the numerator to a FLOAT:

``` sql
SELECT [All Proteins]
     , CAST([CG2 total SpC] AS FLOAT)/[protein length] AS [CG2 SpC/L]
     , CAST([CG5 total SpC] AS FLOAT)/[protein length] AS [CG5 SpC/L]
     , ...
FROM [emmats@washington.edu].[All proteins with length]
```

**Comment by dhalperi** [comment]
For (2), say you save that query as a new dataset called `[emmats@washington.edu].[All proteins SpC/L]`. Then to get the sum, you can use `SUM`:

``` sql
SELECT SUM([CG2 SpC/L]) as [SUM CG2 SpC/L]
      , SUM([CG5 SpC/L]) as [SUM CG5 SpC/L]
      , ...
FROM [emmats@washington.edu].[All proteins SpC/L]
```

**Comment by dhalperi** [comment]
I updated the code on GitHub, I made a few mistakes. Please ignore the version of query (2) that you got in your email! :)

**Comment by dhalperi** [comment]
And then for 3, you just divide the first thing by the second thing. Say you saved (2) as `[emmats@washington.edu].[All proteins SUM SpC/L]`, then

``` sql
SELECT [All Proteins]
     , spc.[CG2 SpC/L] / allspc.[SUM CG2 SpC/L] AS [Relative CG2 SpC/L]
     , ...
FROM [emmats@washington.edu].[All proteins SpC/L] spc
   , [emmats@washington.edu].[All proteins SUM SpC/L] allspc
```
