### ISSUE TITLE
Possible hidden character preventing table join?

### ISSUE THREAD

**Issue by kubu4** [uwescience/sqlshare#17]
Hi!

I'm trying to join two tables:
https://sqlshare.escience.washington.edu/sqlshare#s=query/lisa418%40washington.edu/BlackAB_DESeq.txt

and

https://sqlshare.escience.washington.edu/sqlshare#s=query/lisa418%40washington.edu/BlackAB_Tax

We're using the following SQL statement to perform the join:

SELECT \* FROM [lisa418@washington.edu].[BlackAB_Tax]​a,
  [lisa418@washington.edu].[table_BlackAB_DESeq.txt]b
  WHERE a.​CONTIG=b.id​

The result of the join is an empty dataset with just the header row.  In Excel, I can take any value from [a.CONTIG], perform a find with that value in [b.id] and find the match (using match entire cell contents) without issue.  So, I know the two tables share some of the same values, suggesting that the join should run without issue.

However, when using Excel to sort the datasets based on [a.CONTIG] and [b.id], the datasets do NOT sort in the same fashion.  The [a.CONTIG] sorts in the expected alphabetical fashion (e.g. BlackAbalone_v3_Contig_1, BlackAbalone_v3_Contig_2).  The [b.id] sorts in a decipherable pattern, but it's not "normal" (e.g. BlackAbalone_v3_Contig_1, BlackAbalone_v3_Contig_10, BlackAbalone_v3_Contig_100, BlackAbalone_v3_Contig_2, BlackAbalone_v3_Contig_200, etc).

Thus, I'm wondering if there's a hidden character or something in [a.CONTIG] and/or [b.id] that is preventing the join (and contributing to the different sorting behavior seen in Excel).

If you have a second, could you please do some of your magic and see if you can get this join to work?

**Comment by dhalperi** [comment]
I ran this query to look at `[BlackAB_Tax]`:

``` sql
SELECT TOP 100 a.[CONTIG]
FROM [lisa418@washington.edu].[BlackAB_Tax] a​
```

It looks like the `CONTIG` field values all have a space and then the string `gi` after them. Is that in the input Excel file?

**Comment by dhalperi** [comment]
Hi @kubu4 , any update here?

**Comment by kubu4** [comment]
Sorry, Dan.  I thought I hit "Close & Comment" last time, but it doesn't seem to have saved that.

Anyway, we figured out a quick workaround in Excel prior to  your response.  Didn't even think to look at just that single column in SQLShare so that we could see the entire entry in those rows.  Thanks for that little reminder; it will come in handy in the future!

We're still not sure why the string "gi" is showing up in SQLShare and not in Excel, but we're not going to bother trying to figure that out.  I think it will lead us into a wormhole that we don't have time to deal with.

Thanks again for your quick and useful response!!!
