### ISSUE TITLE
sqlshare doesn't follow links properly after logging in

### ISSUE THREAD

**Issue by dhalperi** [uwescience/sqlshare#28]
Steps to reproduce:
1. Log out of SQLShare (delete cookies) or use incognito mode
2. Follow a SQLShare link, e.g., https://sqlshare.escience.washington.edu/sqlshare/#s=query/billhowe/tweets.csv
3. Log into SQLShare
4. Don't get redirected to https://sqlshare.escience.washington.edu/sqlshare/#s=query/billhowe/tweets.csv after success.

@vegitron , I know you're busy but you might be the first one to get to look at this. Not assigning it, however, in case I get to it first :)

**Comment by vegitron** [comment]
One thing I was thinking of doing, which would side-step this issue, is moving to html5 urls.  So the tweets.csv url would be https://sqlshare.escience.washington.edu/sqlshare/query/billhowe/tweets.csv instead.  I think most browsers support that now, and for ones that don't, the fallback is just another page load.

An alternative, or supplement, to that would be making an alternative to the @login_required function that sent a page to the browser that used javascript to add the hash to a form for submission to an @login_required page, then on the return redirected the browser to the original hash url.

I might be able to work on one or both of those next week, depending on how some other projects work out.

**Comment by vegitron** [comment]
this commit https://github.com/uwescience/sqlshare-web/commit/7b0914038ac38f0111709250c81e517115e5c28d uses the new login decorator.  I'll try to get it out to production later today.
