### ISSUE TITLE
Using REST.svc/v2/db/dataset for tags and popular queries is inefficient and slow

### ISSUE THREAD

**Issue by vegitron** [uwescience/sqlshare#29]
To draw the YOUR TOP VIEWED and POPULAR TAGS content in the web app sidebar, we do a GET on REST.svc/v2/db/dataset.  That takes about 5.5 seconds to process, and another second to send the content, and then the JS goes through every available dataset to get the tags, and find the most popular.

Can we have a new resource that just returns the top tags, and most popular datasets?

**Comment by dhalperi** [comment]
A'la https://github.com/uwescience/sqlshare-web/commit/04727cd1dd7ae9e68a99581fbb8e26ac936d70bd
and https://github.com/uwescience/sqlshare-web/commit/15934b38934437228c7129380b33ee0800899b21

**Comment by billhowe** [comment]
Shrainik: Can you take a look at this?

1) Look at the code for GET .svc/v2/db/dataset and see what query is used
to generate the response.  A slight variation of that query can be used to
get top viewed and popular tags.    Dan and I can help with the SQL-Fu if
needed.

Then

2) We can create new API calls explicitly for these operations as Patrick
suggests

**_OR**_

2) We can have Patrick issue these queries directly using sql via one of
the SQL endpoints

GET /v1/db?sql=...
POST /v2/db
   with sql in the body

There are pros and cons with both of these -- thoughts anyone??

**Comment by shrjain** [comment]
From what I could see, the rows of the table sqlshare.[datasets_access_counts] in reverse sorted order map directly to whatever we show on the sidebar for YOUR TOP VIEWS.
The query for this is straight forward:
SELECT [dataset],[count]
  FROM [sqlshare].[sqlshare].[datasets_access_counts]
  where username = 'shrainik@gmail.com'
  order by [count] desc
GO

Similarly for the POPULAR TAGS:
SELECT [tag],count(*) as [count]
  FROM [sqlshare].[sqlshare].[tags]
  group by [tag]
  order by [count] desc
GO

These don't require querying the datasets at all.
Also, I think having separate APIs for these makes more sense. 

If the above queries look correct (results are correct, I verified, but I wanted to confirm if everyone thinks this is the best way to do this. Looks simple enough to me), I can go ahead and add the two GET APIs for topviews and populartags respectively.

**Comment by dhalperi** [comment]
LGTM

**Comment by shrjain** [comment]
Added the two new resources:
GET:/Rest.svc/PopularTags
GET:/Rest.svc/YourTopViewed

The first call doesn't require any user context, but the second one automatically gives results for the currently logged in user. I can change that to take username as a param if needed. 

I have tested these locally and pushed them to staging. You can try them here:
https://c8f74f55ccf0451387bc2224a509d6ed.cloudapp.net/rest.svc/YourTopViewed
https://c8f74f55ccf0451387bc2224a509d6ed.cloudapp.net/rest.svc/PopularTags

I can do a swap to production with these serve the purpose. Let me know.

Code changes: https://github.com/uwescience/sqlshare-backend/commit/2e87a38f928176c5a06791cb04d4c9de387d115e

**Comment by billhowe** [comment]
Excellent!!!!  Thanks a bunch.

**Comment by dhalperi** [comment]
Although, re: URIs. Might be better to use more predictable names that fit with existing APIs.

already have: GET /tags
How about GET /tags/popular
and GET /tags/user ?

Dan

**Comment by dhalperi** [comment]
(by `/tags/user` i meant `/tags/<user>` e.g., `/tags/dhalperi@washington.edu`).

Dan

**Comment by shrjain** [comment]
Makes sense.
Updated. Try the sample calls:
https://c8f74f55ccf0451387bc2224a509d6ed.cloudapp.net/rest.svc/tags/popular
https://c8f74f55ccf0451387bc2224a509d6ed.cloudapp.net/rest.svc/tags/samwhite@washington.edu

**Comment by dhalperi** [comment]
Are you returning all results? This will eventually not scale for the same reasons the existing calls don't...

Can you add a `limit` parameter to both of these that returns only the `TOP k` results?

e.g., `GET /tags/popular?limit=10`

**Comment by shrjain** [comment]
Ya I wanted to bring that up. Thanks for reminding. I have updated the staging deployment accordingly. 
Both the resources now have a limit param. 
/rest.svc/YourTopViewed?limit=2
/rest.svc/tags/popular?limit=10

**Comment by dhalperi** [comment]
I checked `/popular` and `/tags/samwhite@washington.edu`. Both look good, even for negative values of limit. (`0` is interpreted, as I expected, as all results. Good job!)

Is the "`YourTopViewed`" endpoint still there? Let's remove it. Naming scheme and case, etc., don't fit with the existing API.

**Comment by shrjain** [comment]
YourTopViewed endpoint shows the datasets I guess (its independent of case). Do you mean I should remove it completely? or make it adhere to a more sensible naming scheme?

**Comment by dhalperi** [comment]
I am under the impression it's now redundant with `/tags/<user>`, wherein `user` = yourself. If so, remove it?

As a point of comparison, there's a `GET ../dataset/<user>` call, but not a `GET ../YourDatasets`

**Comment by dhalperi** [comment]
(As a side note, it generally does not make sense to put this API call at the root. It should be clear from the URI that it returns tags, as opposed to datasets for instance.)

**Comment by shrjain** [comment]
I see. 
/Tags/myself is different from /YourTopViewed. First call returns the my tags alone, while the second call returns the datasets I accessed and the access_counts.

the GET /v2/db/dataset/{schema} returns the datasets owned by that user (schema). Which is different from the top viewed datasets by that user.

Should change the GET ../YourTopViewed to GET ../v2/db/dataset/topviewed ?

**Comment by dhalperi** [comment]
Aha, okay, that makes sense and agree that we need these API calls.

Yes, I like the new URI for top datasets viewed by the logged-in user.

**Comment by shrjain** [comment]
Cool. Done and pushed to staging. 

Final APIs:
GET: ../v2/db/dataset/topviewed?limit={limit}
GET: ../tags/popular?limit={limit}
GET: ../tags/{username}?limit={limit}

**Comment by shrjain** [comment]
corner case. what if username is 'popular' ?

**Comment by dhalperi** [comment]
Good point! What does GET /tags return? It might be a 404. In which case...
why not use that one instead of /tags/popular?

Dan

**Comment by billhowe** [comment]
Great work guys!!

One other comment that you are probably already on top of: We need to keep
the API documentation up to date.

http://escience.washington.edu/get-help-now/sql-share-rest-api

Aside: I figure the eventual goal is to automatically generate the
documentation from the comments in the code, a la javadoc.  Sagar made some
progress on this, but there were some issues.  Tracking down the status of
his work may be a good first step; feel free to reach out to him.

**Comment by shrjain** [comment]
Dan, /tags was indeed a 404. I have changed GET: Popular Tags URI to /tags?limit={limit}.

Bill, I will contact Sagar and ask around. I have previously used a great tool called ghostdoc for automatic help file generation. http://submain.com/products/ghostdoc.aspx, I have a bias towards using that, but the API documentation we have also has usage instructions and examples, which would still need to be done manually.

**Comment by dhalperi** [comment]
Closed in favor of https://github.com/uwescience/sqlshare-web/issues/5
