### ISSUE TITLE
SQL privacy warning

### ISSUE THREAD

**Issue by emmats** [uwescience/sqlshare#41]
Hi,
Should I be concerned about this warning? Or is it OK to just continue to the page?
https://www.evernote.com/shard/s242/sh/0b82a200-b09b-4380-aafc-a9eb50dece49/7a499c78874c4213492ff1f42bd20b46
Thanks
Emma

**Comment by dhalperi** [comment]
Yeah, go ahead. We'll move quickly to fix up the certificate. Thanks!
Dan

**Comment by dhalperi** [comment]
Hi Emma,

SQLShare's certificate has been updated so that you should no longer see this warning. Thanks again for the report -- you made us aware of the issue and kickstarted the fix!!

Dan
