### ISSUE TITLE
Tag query produces error message

### ISSUE THREAD

**Issue by sr320** [uwescience/sqlshare#42]
When I click on a tag in the left side bar I receive an error. 

see screenshot.

![ss](http://eagle.fish.washington.edu/cnidarian/skitch/Queries_tagged__qdod2_1A5B510A.png)

**Comment by dhalperi** [comment]
Hmmm. @shrjain any insight? Looks like the REST server claims that this API does not exist. Any chance we pruned it but it is actually used?

``` html
<html version="-//W3C//DTD XHTML 2.0//EN" xml:lang="en" xsi:schemaLocation="http://www.w3.org/1999/xhtml http://www.w3.org/MarkUp/SCHEMA/xhtml2.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><HEAD><TITLE>Request Error</TITLE></HEAD><BODY><DIV id="content"><P class="heading1"><B>Error Description:</B> 'Resource does not exist'</P><P><B>This may be because an invalid URI or HTTP method was specified. Please see the <A HREF="https://rd00155d48d668/REST.svc/help">service help page</A> for constructing valid requests to the service.</B></P><!-- Padding xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--></DIV></BODY></html>
```

**Comment by dhalperi** [comment]
You can also navigate directly there: https://rest.sqlshare.escience.washington.edu/REST.svc/v1/tags/qdod

(I think this should work unauthenticated)

**Comment by shrjain** [comment]
As far as I can see in the past, there has never been an API 
https://rest.sqlshare.escience.washington.edu/REST.svc/v1/tags/{tagname}

I added the popular tags API to make the sidebar appear faster, and that was
https://rest.sqlshare.escience.washington.edu/REST.svc/tags?limit={limit}

I have looked as far as 2013, we haven't removed any APIs. My guess is that this never worked? Or worked via some other API I am unaware of.

**Comment by dhalperi** [comment]
This definitely used to work. Also, is this API not present?

https://github.com/uwescience/sqlshare-backend/blob/a908b2600e77bf0df92f2c8b5998f6e4eac851d9/server/trunk/SQLShareService/RestWebRole/IREST.cs#L464

**Comment by shrjain** [comment]
Yikes. Looks like that API is in a deprecated project folder all together. (deprecated since 2013)

And the one which is always in production is: /server/trunk/SQLShareCloudService/ (this doesn't have the API)

Fixing this now.

**Comment by shrjain** [comment]
Fixed.

**Comment by dhalperi** [comment]
Thanks Shrainik!

—
