### ISSUE TITLE
Login Error : ListenerException

### ISSUE THREAD

**Issue by sr320** [uwescience/sqlshare#44]
When logging into SQLshare 

![sqlshare](https://cloud.githubusercontent.com/assets/4442039/6451595/6255cfec-c0e4-11e4-8d9e-6b9f0c3d4f8a.png)

I get the following error -

`shibsp::ListenerException at (https://sqlshare.escience.washington.edu/sqlshare/uw/)`

---

![lis](http://eagle.fish.washington.edu/cnidarian/skitch/shibsp__ListenerException_and_data-genomic_1AA514F4.png)

**Comment by dhalperi** [comment]
Hmm, I restarted `shibd` on the main sqlshare instance, but that did not fix it. Escalating to UW-IT. THanks @sr320

**Comment by dhalperi** [comment]
Fyi @vegitron

**Comment by vegitron** [comment]
I'm looking at that now.  Looks like we ran out of memory, and with no
swap, processes were killed.  I restarted Apache (which was using the RAM),
MySQL, and shibd, and now it's working.

-Patrick

**Comment by dhalperi** [comment]
Thanks @vegitron  !

**Comment by sr320** [comment]
Thanks!

**Comment by chickadeedee** [comment]
How come we ran out of memory? We got a leak somewhere?

Nina Bohn, QA Lead
Academic and Collaborative Applications, UW-IT
tbohn@uw.edu

On Mar 2, 2015 2:11 PM, Patrick Michaud notifications@github.com wrote:
I'm looking at that now. Looks like we ran out of memory, and with no
swap, processes were killed. I restarted Apache (which was using the RAM),
MySQL, and shibd, and now it's working.

-Patrick

On Mon, Mar 2, 2015 at 2:07 PM, Daniel Halperin notifications@github.com
wrote:

> Fyi @vegitron https://github.com/vegitron
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/uwescience/sqlshare/issues/44#issuecomment-76836991.

##
