### ISSUE TITLE
File preview looks correct, but final uploaded file looks bad

### ISSUE THREAD

**Issue by kubu4** [uwescience/sqlshare#7]
I'm uploading a tab-delimited text file that looks fine in the Dataset Preview window (see screen cap below:

![screenshot_6_7_13_1_46_pm](https://f.cloud.github.com/assets/4514104/626039/64ad398e-cfb3-11e2-8662-6306a401426f.png)

But, after uploading, the data gets transformed/altered in the working dataset (see screen cap below):

![screenshot_6_7_13_1_45_pm](https://f.cloud.github.com/assets/4514104/626041/92399cee-cfb3-11e2-8387-755e6bfd238e.png)

Any thoughts on how to prevent and/or modify the dataset to fix it?  The file name is: UniProtSpeciesList20130607.txt

It's publicly available if anyone wants to check it out.  I can also send the original file that I'm uploading, if anyone is interested.

**Comment by dhalperi** [comment]
Interesting. Can you send me the original file (or a link to it?)

my guess is this: the first few rows parse fine, but something later in the file breaks the parser. Then once the data has been inserted, SQLShare sorts on the first column which brings the later, broken rows to the top of the preview.

**Comment by kubu4** [comment]
Here's the link:

http://eagle.fish.washington.edu/Arabidopsis/UniProtSpeciesList20130607.txt

As always, thanks!!

**Comment by dhalperi** [comment]
Do you know what generated this file? It has neither legal DOS nor legal Unix line endings...

**Comment by dhalperi** [comment]
Actually, I'm now confused. Why do you say that the uploaded data looks bad? I think it's fine, just sorted in a different order.

**Comment by dhalperi** [comment]
If you want the file in the same order as it came, there are generally two answers:
1. If the original file wasn't sorted on any columns, you're out of luck. It's an implementation detail of SQLShare that every dataset has to be sorted on some column.
2. If the original file **was** sorted on some columns, you simply edit your view to include the ordering constraints
   
   ``` sql
   SELECT *
   FROM ...
   ORDER BY [TaxonCode],[Species]
   ```

**Comment by dhalperi** [comment]
Also, it would be much helpful in the future you include the actual URL to the dataset in SQLShare rather than just saying "it's publicly available" :).

**Comment by kubu4** [comment]
As usual, you're totally correct, Dan!  I misinterpreted how the data is shown to the user after it's been uploaded.  I thought each "page" of the dataset view (using the numbers below the table) allowed you to browse through the entire dataset, 100 rows at a time.  Therefore, I was surprised when I didn't see most of the data rows.

Sorry for the hassle and thanks (as always!!) for your quick and helpful response!
