### ISSUE TITLE
keep rows where value contains certain text

### ISSUE THREAD

**Issue by emmats** [uwescience/sqlshare#73]
I would like to keep the rows from the dataset below where the text in the protein column contains the string "RUEPO".  It would also work to create new columns by splitting the protein column based on the delimiter "_" because then the RUEPO would be in its own column.

I've tried a few things I have found online, but most of what I find is specific to other SQLs and not SQLshare.

https://sqlshare.escience.washington.edu/sqlshare/#s=query/emmats%40washington.edu/bact%20detection%20peptides%20and%20proteins

Thanks

**Comment by sr320** [comment]
Hi Emma,

You mean something like this?

```
SELECT * FROM [emmats@washington.edu].[bact detection peptides and proteins]
  Where protein like '%RUEPO%'
```

**Comment by emmats** [comment]
Thanks, Steven, that is exactly what I needed.

**Comment by sr320** [comment]
Feel free to _close_ the issue then :+1:
