### ISSUE TITLE
multiple CASE WHENs

### ISSUE THREAD

**Issue by emmats** [uwescience/sqlshare#8]
Hi Dan,
I'm trying to make a new column based on an existing column with either 0, 1, or 2 in it.  If there is a 0, I want U in the new column, if 1 then M, and if 2 then NM.  I've tried a few iterations of a query and I can't quite get it to work (see below).  Here's my file: https://sqlshare.escience.washington.edu/sqlshare#s=query/emmats%40washington.edu/summed%20presence%20absence%20fragment%20peaks.

SELECT CAS001, 
CASE WHEN CAS001=2 THEN NM, WHEN CAS001=1 THEN M, WHEN CAS001=0 THEN U END
AS CAS001MethStat
FROM [summed presence absence fragment peaks]

Thanks!

**Comment by emmats** [comment]
Steven helped me find the solution!

SELECT CAS001, 
CASE WHEN CAS001=2 THEN NM, WHEN CAS001=1 THEN M, WHEN CAS001=0 THEN U END
AS CAS001MethStat
FROM [summed presence absence fragment peaks]

**Comment by dhalperi** [comment]
@emmats: Very cool! Glad you were able to work it out

It looks like the answer you posted is actually the same as the question. Can you post the actual solution for the next person?

**Comment by emmats** [comment]
You're right!  I guess I copied the wrong thing.  The correct solution is
SELECT CAS001,
CASE WHEN CAS001=2 then 'NM' WHEN CAS001=1 then 'M' else 'U' END
AS CAS001MethStat
FROM [emmats@washington.edu].[summed presence absence fragment peaks]

**Comment by dhalperi** [comment]
Aha. So the big difference is that you're not allowed to use the comma (`,`) between `WHEN` clauses, right?

Thanks Emma!
