### ISSUE TITLE
Computing a function on column

### ISSUE THREAD

**Issue by che625** [uwescience/sqlshare#9]
I am wondering the function for computing an expression for a given column.  Right now I am trying to subtract 1 number to a query on Column 2 and add 1 number to Column 3.  Here is what I have but it isn't working: 

SELECT [Column2 - 1], [Column3 + 1]
  FROM [che625@washington.edu].[table_Galaxy402-_o_Methylated_CG_BED_c_ (3).bed]​

Any suggestions are greatly appreciated!

**Comment by dhalperi** [comment]
I haven't run it, but note that `[blah]` means "the column named blah". So you probably want to be doing `[Column2]-1`. (The placement of brackets is different.)

**Comment by sr320** [comment]
This works

SELECT
Column2 - 1 as NewColumn,  
Column3 + 1 as AnotherNewColumn  
FROM [che625@washington.edu].[Methylated_CG_BED_WholeGenome.bed]​

**Comment by dhalperi** [comment]
@sr320 yes, that should work. But in the general case, you want the `[`,`]` around `Column2` so that the column name can contain spaces, etc. I try to always put it there so I get used to it...

**Comment by dhalperi** [comment]
Hi @che625,

Did @sr320 and I resolve this issue for you? If so, I will close the issue.

For future reference, please try and include a URL link to the actual SQLShare dataset you're deriving data from!

Thanks,
Dan

**Comment by che625** [comment]
Yes, I figured it out, you can close the issue.  Thanks @dhalperi!
